export const mySurveyConstants = {

   
    GET_SURVEYS_REQUEST_STARTED: 'GET_SURVEYS_REQUEST_STARTED',
    SUCCESS_GET_SURVEYS_REQUEST: 'SUCCESS_GET_SURVEYS_REQUEST',
    ADD_SURVEYS_LIST: 'ADD_SURVEYS_LIST',
    FAILURE_GET_SURVEYS_REQUEST: 'FAILURE_GET_SURVEYS_REQUEST',
    GET_SURVEYS_REQUEST_ENDED: 'GET_SURVEYS_REQUEST_ENDED',
    CLEAR_SURVEY_LIST: 'CLEAR_SURVEY_LIST',

    GET_SURVEY_REQUEST_STARTED: 'GET_SURVEY_REQUEST_STARTED',
    SUCCESS_GET_SURVEY_REQUEST: 'SUCCESS_GET_SURVEY_REQUEST',
    ADD_OPEN_SURVEY: 'ADD_OPEN_SURVEY',
    FAILURE_GET_SURVEY_REQUEST: 'FAILURE_GET_SURVEY_REQUEST',
    GET_SURVEY_REQUEST_ENDED: 'GET_SURVEY_REQUEST_ENDED',
   
    GET_SURVEY_RESPONSES_REQUEST_STARTED: 'GET_SURVEY_RESPONSES_REQUEST_STARTED',
    SUCCESS_GET_SURVEY_RESPONSES_REQUEST: 'SUCCESS_GET_SURVEY_RESPONSES_REQUEST',
    SET_SURVEY_RESPONSE_LIST: 'SET_SURVEY_RESPONSE_LIST',
    FAILURE_GET_SURVEY_RESPONSES_REQUEST: 'FAILURE_GET_SURVEY_RESPONSES_REQUEST',
    GET_SURVEY_RESPONSES_REQUEST_ENDED: 'GET_SURVEY_RESPONSES_REQUEST_ENDED',
    RESET_SURVEY_RESPONSE_LIST: 'RESET_SURVEY_RESPONSE_LIST'
}