export const surveyConstants = {
    ADD_NEW_QUESTION: 'ADD_NEW_QUESTION',
    REMOVE_QUESTION: 'REMOVE_QUESTION',
    ADD_SURVEY_NAME: 'ADD_SURVEY_NAME',
    ADD_SURVEY_DESCRIPTION: 'ADD_SURVEY_DESCRIPTION',
    CLEAR_SURVEY_FORM: 'CLEAR_SURVEY_FORM',

    CREATE_SURVEY_REQUEST_STARTED: 'CREATE_SURVEY_REQUEST_STARTED',
    SUCCESS_CREATE_SURVEY_REQUEST: 'SUCCESS_CREATE_SURVEY_REQUEST',
    FAILURE_CREATE_SURVEY_REQUEST: 'FAILURE_CREATE_SURVEY_REQUEST',
    CREATE_SURVEY_REQUEST_ENDED: 'CREATE_SURVEY_REQUEST_ENDED',
    
    GET_SURVEYS_REQUEST_STARTED: 'GET_SURVEYS_REQUEST_STARTED',
    SUCCESS_GET_SURVEYS_REQUEST: 'SUCCESS_GET_SURVEYS_REQUEST',
    ADD_SURVEYS_LIST: 'ADD_SURVEYS_LIST',
    FAILURE_GET_SURVEYS_REQUEST: 'FAILURE_GET_SURVEYS_REQUEST',
    GET_SURVEYS_REQUEST_ENDED: 'GET_SURVEYS_REQUEST_ENDED',
    CLEAR_SURVEY_LIST: 'CLEAR_SURVEY_LIST',

    GET_SURVEY_REQUEST_STARTED: 'GET_SURVEY_REQUEST_STARTED',
    SUCCESS_GET_SURVEY_REQUEST: 'SUCCESS_GET_SURVEY_REQUEST',
    ADD_OPEN_SURVEY: 'ADD_OPEN_SURVEY',
    FAILURE_GET_SURVEY_REQUEST: 'FAILURE_GET_SURVEY_REQUEST',
    GET_SURVEY_REQUEST_ENDED: 'GET_SURVEY_REQUEST_ENDED',

    TAKE_SURVEY_REQUEST_STARTED: 'TAKE_SURVEY_REQUEST_STARTED',
    SUCCESS_TAKE_SURVEY_REQUEST: 'SUCCESS_TAKE_SURVEY_REQUEST',
    FAILURE_TAKE_SURVEY_REQUEST: 'FAILURE_TAKE_SURVEY_REQUEST',
    TAKE_SURVEY_REQUEST_ENDED: 'TAKE_SURVEY_REQUEST_ENDED',
    RESET_TAKE_SURVEY_FORM: 'RESET_TAKE_SURVEY_FORM'
}