export const userConstants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    TOKEN_AUTH_REQUEST: 'TOKEN_AUTH_REQUEST',
    TOKEN_AUTH_FAILURE: 'TOKEN_AUTH_FAILURE',
    TOKEN_AUTH_SUCCESS: 'TOEKN_AUTH_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}